
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nhts!123456
      - MSSQL_PID=Developer
    ports:
      - 14303:1433
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Nhts!123456 -C -Q 'SELECT 1'"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Nhts!123456 -C -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "Init script executed";
      '


volumes:
  mssql_data:

networks:
  nhts-store-network:
    driver: bridge


