spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:14303;databaseName=nhts-store;trustServerCertificate=true
    username: sa
    password: Nhts!123456
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: off
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true





