spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33006/nhts_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Nhts!123
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: off
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true