/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom4.nhtsstore.ui;

import com.nhom4.nhtsstore.ui.shared.LanguageManager;
import org.springframework.stereotype.Controller;

/**
 *
 * @author Admin
 */
@Controller
public class Form extends javax.swing.JPanel {
    private final LanguageManager languageManager;
    /**
     * Creates new form Form
     */
    public Form(LanguageManager languageManager) {
        this.languageManager = languageManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables

    // End of variables declaration//GEN-END:variables
}
