/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom4.nhtsstore.ui.pointOfSale;

import com.nhom4.nhtsstore.services.IProductImageService;
import com.nhom4.nhtsstore.services.impl.OrderService;
import com.nhom4.nhtsstore.ui.ApplicationState;
import com.nhom4.nhtsstore.ui.navigation.NavigationService;
import com.nhom4.nhtsstore.ui.navigation.RoutablePanel;
import com.nhom4.nhtsstore.ui.navigation.RouteParams;
import com.nhom4.nhtsstore.viewmodel.cart.CartItemVm;
import com.nhom4.nhtsstore.viewmodel.cart.CartVm;
import com.nhom4.nhtsstore.viewmodel.user.UserSessionVm;
import jakarta.annotation.PostConstruct;

import java.math.BigDecimal;
import java.util.*;
import javax.swing.*;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import raven.modal.Toast;
import raven.modal.toast.option.ToastLocation;

/**
 *
 * @author Sang
 */
@Scope("prototype")
@Component
public class CartPanel extends javax.swing.JPanel implements RoutablePanel{

    /**
     * Creates new form CartPanel
     */
    private final NavigationService navigationService;
    private final OrderService orderService;
    private final ApplicationState applicationState;
    private final IProductImageService productImageService;
    private UserSessionVm currentUser;
    private CartVm cart;
    public CartPanel(NavigationService navigationService, OrderService orderService, ApplicationState applicationState, IProductImageService productImageService) {
        this.navigationService = navigationService;
        this.orderService = orderService;
        this.applicationState = applicationState;
        this.productImageService = productImageService;
        initComponents();
        cart = applicationState.getCart();
    }

    @PostConstruct
    public void init() {
        pnlTableContent.setLayout(new BoxLayout(pnlTableContent, BoxLayout.Y_AXIS));
        currentUser = applicationState.getCurrentUser();
        loadCart();
        jScrollPane1.setViewportView(pnlTableContent);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

    }

    private void loadCart() {
        pnlTableContent.removeAll();

        // Get latest cart from application state
        cart = applicationState.getCart();

        for (CartItemVm item : cart.getItems()) {
            var images = productImageService.findByProductId(item.getProductId());
            CartBody cartBody = new CartBody(item, images, this::removeCartItem, this::updateCartItemQuantity);
            pnlTableContent.add(cartBody);
            pnlTableContent.add(Box.createVerticalStrut(10));
        }

        updateDisplayTotals();

        pnlTableContent.revalidate();
        pnlTableContent.repaint();
    }
    private void updateDisplayTotals() {
        int totalItems = cart.getItems().size();
        lblTotalNumber.setText("Total (" + totalItems + " products): ");
        lblTotalPrice.setText(String.format("%.2f$", cart.getTotalAmount()));
    }




    private void removeCartItem(CartItemVm item) {
        cart.getItems().removeIf(i -> i.getProductId().equals(item.getProductId()));

        // Update total amount
        updateCartTotal();

        // Update cart in application state which will trigger the listener to save to file
        applicationState.setCart(cart);

        loadCart();
    }
    private void updateCartTotal() {
        BigDecimal total = cart.getItems().stream()
                .map(item -> item.getPrice().multiply(BigDecimal.valueOf( item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        cart.setTotalAmount(total);
        cart.setLastModifiedDate(new Date());
    }


    private void updateCartItemQuantity(Long productId, int newQuantity) {
        cart.getItems().stream()
                .filter(item -> item.getProductId().equals(productId))
                .findFirst()
                .ifPresent(item -> {
                    item.setQuantity(newQuantity);

                    // Update total amount
                    updateCartTotal();

                    // Update cart in application state which will trigger the listener to save to file
                    applicationState.setCart(cart);
                });

        loadCart();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        lblAmount1 = new javax.swing.JLabel();
        pnlTableHeader1 = new javax.swing.JPanel();
        lblTotalNumber = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnBuyNow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTableContent = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Product name");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrice.setText("Price");

        lblAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAmount.setText("Amount");

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Action");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAmount1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAmount1.setText("Quantity");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jCheckBox1)
                .addGap(45, 45, 45)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrice)
                        .addComponent(lblAmount)
                        .addComponent(btnDelete)
                        .addComponent(lblAmount1))
                    .addComponent(jCheckBox1))
                .addContainerGap(48, Short.MAX_VALUE))
        );

//        pnlTableHeader1.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalNumber.setText("Total (0 products): ");

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(255, 102, 102));
        lblTotalPrice.setText("0đ");

        btnBuyNow.setBackground(new java.awt.Color(246, 127, 26));
        btnBuyNow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuyNow.setForeground(new java.awt.Color(255, 255, 255));
        btnBuyNow.setText("Buy Now");
        btnBuyNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuyNowMouseClicked(evt);
            }
        });
        btnBuyNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTableHeader1Layout = new javax.swing.GroupLayout(pnlTableHeader1);
        pnlTableHeader1.setLayout(pnlTableHeader1Layout);
        pnlTableHeader1Layout.setHorizontalGroup(
            pnlTableHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableHeader1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPrice)
                .addGap(18, 18, 18)
                .addComponent(btnBuyNow)
                .addGap(46, 46, 46))
        );
        pnlTableHeader1Layout.setVerticalGroup(
            pnlTableHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableHeader1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(pnlTableHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalNumber)
                    .addComponent(lblTotalPrice)
                    .addComponent(btnBuyNow))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTableContentLayout = new javax.swing.GroupLayout(pnlTableContent);
        pnlTableContent.setLayout(pnlTableContentLayout);
        pnlTableContentLayout.setHorizontalGroup(
            pnlTableContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTableContentLayout.setVerticalGroup(
            pnlTableContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlTableContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTableHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlTableHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnBuyNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyNowMouseClicked

    }//GEN-LAST:event_btnBuyNowMouseClicked

    private void btnBuyNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNowActionPerformed
        if (cart.getItems().isEmpty()) {
            Toast.show(CartPanel.this, Toast.Type.ERROR,
                    "Cart is empty!",
                    ToastLocation.TOP_CENTER);
            return;
        }

        RouteParams params = new RouteParams();
        navigationService.navigateTo(InvoicePanel.class, params);
    }//GEN-LAST:event_btnBuyNowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyNow;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTotalNumber;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlTableContent;
    private javax.swing.JPanel pnlTableHeader1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onNavigate(RouteParams params) {
        currentUser = applicationState.getCurrentUser();
        loadCart();

    }
}
