ALTER TABLE [product] ALTER COLUMN [name] NVARCHAR(255);
ALTER TABLE [product] ALTER COLUMN [manufacturer] NVARCHAR(255);
ALTER TABLE [supplier] ALTER COLUMN [name] NVARCHAR(255);
ALTER TABLE [supplier] ALTER COLUMN [address] NVARCHAR(255);
ALTER TABLE [users] ALTER COLUMN [full_name] NVARCHAR(100);
ALTER TABLE [roles] ALTER COLUMN [description] NVARCHAR(255);
ALTER TABLE [permissions] ALTER COLUMN [description] NVARCHAR(255);
ALTER TABLE [category] ALTER COLUMN [name] NVARCHAR(255);



